pipeline {
    agent {
        docker { image 'openjdk:11' }
    }

    stages {
        stage('Execute') {
            steps {
                        sh '''
                            javac HelloWorld.java
                            java HelloWorld
                        '''
                    }
        }
    }

    post {
        always {
            echo "Docker-based Java build complete."
        }
    }
}
